name: Deploy DevOps Intake Form

on:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install HTML Validator
        run: pip install html5validator

      - name: Validate HTML
        run: html5validator --root . --also-check-css

      - name: Done
        run: echo "HTML validated successfully."
